global using System;
global using System.Collections.Generic;
global using System.Collections.Concurrent;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using PluginManifest = RobloxAccountManager.PluginSdk.PluginManifest;
global using ManagedAccountSnapshot = RobloxAccountManager.PluginSdk.ManagedAccountSnapshot;
global using PluginThemePalette = RobloxAccountManager.PluginSdk.ThemePalette;
global using PluginActionDescriptor = RobloxAccountManager.PluginSdk.ActionDescriptor;
global using PluginActionInvocation = RobloxAccountManager.PluginSdk.ActionInvocation;
global using PluginActionResult = RobloxAccountManager.PluginSdk.ActionResult;
global using AccountProfile = RobloxAccountManager.Core.Models.AccountProfile;
global using GamePreset = RobloxAccountManager.Core.Models.GamePreset;
global using GameSettings = RobloxAccountManager.Core.Models.GameSettings;
global using LauncherSettings = RobloxAccountManager.Core.Models.LauncherSettings;
