<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RobloxAccountManager</AssemblyName>
    <Product>Roblox Account Manager</Product>
    <Description>Open-source Roblox account and multi-client launcher.</Description>
    <ApplicationIcon>Assets\RobloxAccountManager.ico</ApplicationIcon>
    <RootNamespace>RobloxAltClient</RootNamespace>
    <Version>1.1.1</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowedReferenceRelatedFileExtensions></AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\RobloxAccountManager.ico" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
  </ItemGroup>

  <Target Name="RemoveWebViewDocumentationFromPublish" AfterTargets="Publish">
    <ItemGroup>
      <PublishedWebViewDocumentation Include="$(PublishDir)Microsoft.Web.WebView2.*.xml" />
    </ItemGroup>
    <Delete Files="@(PublishedWebViewDocumentation)" />
  </Target>
</Project>
